- project:
    name: kubernetes-sigs/cluster-api-provider-openstack
    check:
      jobs:
        - cluster-api-provider-openstack-current-acceptance-test-v1.18

- job:
    name: cluster-api-provider-openstack-conformance-pr
    parent: init-test
    timeout: 36000
    description: |
      Test CAPO & Kubernetes
    run: .zuul/playbooks/run.yaml
    nodeset: ubuntu-bionic-large
    vars:
      go_version: '1.13.15'
      k8s_log_dir: '{{ ansible_user_dir }}/workspace/logs/_artifacts'
      k8s_os_capi_provider_src_dir: '{{ ansible_user_dir }}/src/sigs.k8s.io/cluster-api-provider-openstack'
      extra_args: ''

- job:
    name: cluster-api-provider-openstack-current-acceptance-test-v1.18
    parent: cluster-api-provider-openstack-conformance-pr
    description: |
      Test CAPO current against Kubernetes release-1.18
    vars:
      k8s_version_series: '1.18'
      extra_args: '--use-ci-artifacts'
