# permissions for end users to view openstackimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackimage-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - openstackimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - openstackimages/status
  verbs:
  - get
