//go:build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
"k8s.io/apimachinery/pkg/runtime"
"k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPool) DeepCopyInto(out *OpenStackFloatingIPPool) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
in.Spec.DeepCopyInto(&out.Spec)
in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPool.
func (in *OpenStackFloatingIPPool) DeepCopy() *OpenStackFloatingIPPool {
	if in == nil { return nil }
	out := new(OpenStackFloatingIPPool)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackFloatingIPPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPoolList) DeepCopyInto(out *OpenStackFloatingIPPoolList) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ListMeta.DeepCopyInto(&out.ListMeta)
if in.Items != nil {
in, out := &in.Items, &out.Items
*out = make([]OpenStackFloatingIPPool, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPoolList.
func (in *OpenStackFloatingIPPoolList) DeepCopy() *OpenStackFloatingIPPoolList {
	if in == nil { return nil }
	out := new(OpenStackFloatingIPPoolList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackFloatingIPPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPoolSpec) DeepCopyInto(out *OpenStackFloatingIPPoolSpec) {
*out = *in
if in.PreAllocatedFloatingIPs != nil {
in, out := &in.PreAllocatedFloatingIPs, &out.PreAllocatedFloatingIPs
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.MaxIPs != nil {
in, out := &in.MaxIPs, &out.MaxIPs
*out = new(int)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPoolSpec.
func (in *OpenStackFloatingIPPoolSpec) DeepCopy() *OpenStackFloatingIPPoolSpec {
	if in == nil { return nil }
	out := new(OpenStackFloatingIPPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPoolStatus) DeepCopyInto(out *OpenStackFloatingIPPoolStatus) {
*out = *in
if in.ClaimedIPs != nil {
in, out := &in.ClaimedIPs, &out.ClaimedIPs
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.AvailableIPs != nil {
in, out := &in.AvailableIPs, &out.AvailableIPs
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.FailedIPs != nil {
in, out := &in.FailedIPs, &out.FailedIPs
*out = make([]string, len(*in))
copy(*out, *in)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPoolStatus.
func (in *OpenStackFloatingIPPoolStatus) DeepCopy() *OpenStackFloatingIPPoolStatus {
	if in == nil { return nil }
	out := new(OpenStackFloatingIPPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackServer) DeepCopyInto(out *OpenStackServer) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
in.Spec.DeepCopyInto(&out.Spec)
in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackServer.
func (in *OpenStackServer) DeepCopy() *OpenStackServer {
	if in == nil { return nil }
	out := new(OpenStackServer)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackServerList) DeepCopyInto(out *OpenStackServerList) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ListMeta.DeepCopyInto(&out.ListMeta)
if in.Items != nil {
in, out := &in.Items, &out.Items
*out = make([]OpenStackServer, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackServerList.
func (in *OpenStackServerList) DeepCopy() *OpenStackServerList {
	if in == nil { return nil }
	out := new(OpenStackServerList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackServerSpec) DeepCopyInto(out *OpenStackServerSpec) {
*out = *in
if in.AdditionalBlockDevices != nil {
in, out := &in.AdditionalBlockDevices, &out.AdditionalBlockDevices
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.AvailabilityZone != nil {
in, out := &in.AvailabilityZone, &out.AvailabilityZone
*out = new(string)
**out = **in
}
if in.ConfigDrive != nil {
in, out := &in.ConfigDrive, &out.ConfigDrive
*out = new(bool)
**out = **in
}
if in.Flavor != nil {
in, out := &in.Flavor, &out.Flavor
*out = new(string)
**out = **in
}
if in.FlavorID != nil {
in, out := &in.FlavorID, &out.FlavorID
*out = new(string)
**out = **in
}
if in.FloatingIPPoolRef != nil {
in, out := &in.FloatingIPPoolRef, &out.FloatingIPPoolRef
*out = new(v1.TypedLocalObjectReference)
(*in).DeepCopyInto(*out)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackServerSpec.
func (in *OpenStackServerSpec) DeepCopy() *OpenStackServerSpec {
	if in == nil { return nil }
	out := new(OpenStackServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackServerStatus) DeepCopyInto(out *OpenStackServerStatus) {
*out = *in
if in.InstanceID != nil {
in, out := &in.InstanceID, &out.InstanceID
*out = new(string)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackServerStatus.
func (in *OpenStackServerStatus) DeepCopy() *OpenStackServerStatus {
	if in == nil { return nil }
	out := new(OpenStackServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedServerSpec) DeepCopyInto(out *ResolvedServerSpec) {
*out = *in
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedServerSpec.
func (in *ResolvedServerSpec) DeepCopy() *ResolvedServerSpec {
	if in == nil { return nil }
	out := new(ResolvedServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerResources) DeepCopyInto(out *ServerResources) {
*out = *in
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerResources.
func (in *ServerResources) DeepCopy() *ServerResources {
	if in == nil { return nil }
	out := new(ServerResources)
	in.DeepCopyInto(out)
	return out
}

