//go:build !ignore_autogenerated

/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageAdditionalProperty) DeepCopyInto(out *ImageAdditionalProperty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageAdditionalProperty.
func (in *ImageAdditionalProperty) DeepCopy() *ImageAdditionalProperty {
	if in == nil {
		return nil
	}
	out := new(ImageAdditionalProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageContent) DeepCopyInto(out *ImageContent) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(ImageHash)
		**out = **in
	}
	if in.GlanceHashAlgorithm != nil {
		in, out := &in.GlanceHashAlgorithm, &out.GlanceHashAlgorithm
		*out = new(ImageHashAlgorithm)
		**out = **in
	}
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageContent.
func (in *ImageContent) DeepCopy() *ImageContent {
	if in == nil {
		return nil
	}
	out := new(ImageContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageHash) DeepCopyInto(out *ImageHash) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageHash.
func (in *ImageHash) DeepCopy() *ImageHash {
	if in == nil {
		return nil
	}
	out := new(ImageHash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageProperties) DeepCopyInto(out *ImageProperties) {
	*out = *in
	if in.MinDiskGB != nil {
		in, out := &in.MinDiskGB, &out.MinDiskGB
		*out = new(int)
		**out = **in
	}
	if in.MinRAMMB != nil {
		in, out := &in.MinRAMMB, &out.MinRAMMB
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageProperties.
func (in *ImageProperties) DeepCopy() *ImageProperties {
	if in == nil {
		return nil
	}
	out := new(ImageProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSource) DeepCopyInto(out *ImageSource) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(ImageSourceURL)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSource.
func (in *ImageSource) DeepCopy() *ImageSource {
	if in == nil {
		return nil
	}
	out := new(ImageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSourceURL) DeepCopyInto(out *ImageSourceURL) {
	*out = *in
	if in.Decompress != nil {
		in, out := &in.Decompress, &out.Decompress
		*out = new(ImageCompression)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSourceURL.
func (in *ImageSourceURL) DeepCopy() *ImageSourceURL {
	if in == nil {
		return nil
	}
	out := new(ImageSourceURL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPool) DeepCopyInto(out *OpenStackFloatingIPPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPool.
func (in *OpenStackFloatingIPPool) DeepCopy() *OpenStackFloatingIPPool {
	if in == nil {
		return nil
	}
	out := new(OpenStackFloatingIPPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackFloatingIPPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPoolList) DeepCopyInto(out *OpenStackFloatingIPPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackFloatingIPPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPoolList.
func (in *OpenStackFloatingIPPoolList) DeepCopy() *OpenStackFloatingIPPoolList {
	if in == nil {
		return nil
	}
	out := new(OpenStackFloatingIPPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackFloatingIPPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPoolSpec) DeepCopyInto(out *OpenStackFloatingIPPoolSpec) {
	*out = *in
	if in.PreAllocatedFloatingIPs != nil {
		in, out := &in.PreAllocatedFloatingIPs, &out.PreAllocatedFloatingIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxIPs != nil {
		in, out := &in.MaxIPs, &out.MaxIPs
		*out = new(int)
		**out = **in
	}
	out.IdentityRef = in.IdentityRef
	if in.FloatingIPNetwork != nil {
		in, out := &in.FloatingIPNetwork, &out.FloatingIPNetwork
		*out = new(v1beta1.NetworkParam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPoolSpec.
func (in *OpenStackFloatingIPPoolSpec) DeepCopy() *OpenStackFloatingIPPoolSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackFloatingIPPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFloatingIPPoolStatus) DeepCopyInto(out *OpenStackFloatingIPPoolStatus) {
	*out = *in
	if in.ClaimedIPs != nil {
		in, out := &in.ClaimedIPs, &out.ClaimedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvailableIPs != nil {
		in, out := &in.AvailableIPs, &out.AvailableIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedIPs != nil {
		in, out := &in.FailedIPs, &out.FailedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FloatingIPNetwork != nil {
		in, out := &in.FloatingIPNetwork, &out.FloatingIPNetwork
		*out = new(v1beta1.NetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFloatingIPPoolStatus.
func (in *OpenStackFloatingIPPoolStatus) DeepCopy() *OpenStackFloatingIPPoolStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackFloatingIPPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackImage) DeepCopyInto(out *OpenStackImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackImage.
func (in *OpenStackImage) DeepCopy() *OpenStackImage {
	if in == nil {
		return nil
	}
	out := new(OpenStackImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackImageList) DeepCopyInto(out *OpenStackImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackImageList.
func (in *OpenStackImageList) DeepCopy() *OpenStackImageList {
	if in == nil {
		return nil
	}
	out := new(OpenStackImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackImageSpec) DeepCopyInto(out *OpenStackImageSpec) {
	*out = *in
	if in.ContainerFormat != nil {
		in, out := &in.ContainerFormat, &out.ContainerFormat
		*out = new(ImageContainerFormat)
		**out = **in
	}
	if in.DiskFormat != nil {
		in, out := &in.DiskFormat, &out.DiskFormat
		*out = new(ImageDiskFormat)
		**out = **in
	}
	if in.Protected != nil {
		in, out := &in.Protected, &out.Protected
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]ImageTag, len(*in))
		copy(*out, *in)
	}
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(ImageVisibility)
		**out = **in
	}
	if in.AdditionalProperties != nil {
		in, out := &in.AdditionalProperties, &out.AdditionalProperties
		*out = make([]ImageAdditionalProperty, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackImageSpec.
func (in *OpenStackImageSpec) DeepCopy() *OpenStackImageSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackImageStatus) DeepCopyInto(out *OpenStackImageStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(ImageHash)
		**out = **in
	}
	if in.SizeB != nil {
		in, out := &in.SizeB, &out.SizeB
		*out = new(int64)
		**out = **in
	}
	if in.VirtualSizeB != nil {
		in, out := &in.VirtualSizeB, &out.VirtualSizeB
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackImageStatus.
func (in *OpenStackImageStatus) DeepCopy() *OpenStackImageStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackImageStatus)
	in.DeepCopyInto(out)
	return out
}
