apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: dev-test
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: dev-test-control-plane
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: dev-test-control-plane-machine
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackClusterTemplate
      name: dev-test-openstackcluster
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: dev-test-default-worker-bootstraptemplate
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: OpenStackMachineTemplate
            name: dev-test-default-worker-machine
  variables:
  - name: identityRef
    required: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          name:
            type: string
            description: "The name of the OpenStackCloudConfigSecret."
            default: dev-test-cloud-config
          cloudName:
            type: string
            description: "The name of the cloud in the OpenStackCloudConfigSecret."
            default: capo-e2e
  - name: imageBaseName
    required: false
    schema:
      openAPIV3Schema:
        type: string
        description: |
          The base name of the OpenStack image that is used for creating the servers.
          This will be combined with the k8s version to create the full name. E.g. imageBaseName-v1.31.2.
        default: "ubuntu-2404-kube"
  - name: imageOverride
    required: false
    schema:
      openAPIV3Schema:
        type: string
        description: |
          The image that is used for creating the servers.
          This overrides the imageBaseName + k8s version that is normally used.
  patches:
  - name: image
    description: "Sets the OpenStack image that is used for creating the servers."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/filter/name
        valueFrom:
          template: |
            {{ if .imageOverride }}{{ .imageOverride }}{{ else }}{{ .imageBaseName }}-{{ .builtin.controlPlane.version }}{{ end }}
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
      jsonPatches:
      - op: add
        path: /spec/template/spec/image/filter/name
        valueFrom:
          template: |
            {{ if .imageOverride }}{{ .imageOverride }}{{ else }}{{ .imageBaseName }}-{{ .builtin.machineDeployment.version }}{{ end }}
  - name: identityRef
    description: "Sets the OpenStack identity reference."
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/identityRef
        valueFrom:
          variable: identityRef
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: dev-test-default-worker-bootstraptemplate
spec:
  template:
    spec:
      files: []
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: dev-test-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
        files: []
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{ instance_id }}'
            name: '{{ local_hostname }}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{ instance_id }}'
            name: '{{ local_hostname }}'
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackClusterTemplate
metadata:
  name: dev-test-openstackcluster
spec:
  template:
    spec:
      apiServerLoadBalancer:
        enabled: true
      externalNetwork:
        filter:
          name: ${OPENSTACK_EXTERNAL_NETWORK_NAME:=public}
      identityRef:
        name: dev-test-cloud-config
        cloudName: ${OPENSTACK_CLOUD:=capo-e2e}
      managedSecurityGroups:
        allNodesSecurityGroupRules:
        - description: Created by cluster-api-provider-openstack - BGP (calico)
          direction: ingress
          etherType: IPv4
          name: BGP (Calico)
          portRangeMin: 179
          portRangeMax: 179
          protocol: tcp
          remoteManagedGroups:
          - controlplane
          - worker
        - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
          direction: ingress
          etherType: IPv4
          name: IP-in-IP (calico)
          protocol: "4"
          remoteManagedGroups:
          - controlplane
          - worker
      managedSubnets:
      - cidr: 10.6.0.0/24
        dnsNameservers:
        - 8.8.8.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: dev-test-control-plane-machine
spec:
  template:
    spec:
      flavor: ${OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR:=m1.medium}
      image:
        filter:
          name: overridden-by-patch
      sshKeyName: ${OPENSTACK_SSH_KEY_NAME:=""}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: dev-test-default-worker-machine
spec:
  template:
    spec:
      flavor: ${OPENSTACK_NODE_MACHINE_FLAVOR:=m1.small}
      image:
        filter:
          name: overridden-by-patch
      sshKeyName: ${OPENSTACK_SSH_KEY_NAME:=""}
