// +build !ignore_autogenerated

/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha5

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha4 "sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AddressPair)(nil), (*v1alpha4.AddressPair)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_AddressPair_To_v1alpha4_AddressPair(a.(*AddressPair), b.(*v1alpha4.AddressPair), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.AddressPair)(nil), (*AddressPair)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_AddressPair_To_v1alpha5_AddressPair(a.(*v1alpha4.AddressPair), b.(*AddressPair), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Bastion)(nil), (*v1alpha4.Bastion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_Bastion_To_v1alpha4_Bastion(a.(*Bastion), b.(*v1alpha4.Bastion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Bastion)(nil), (*Bastion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Bastion_To_v1alpha5_Bastion(a.(*v1alpha4.Bastion), b.(*Bastion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalRouterIPParam)(nil), (*v1alpha4.ExternalRouterIPParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_ExternalRouterIPParam_To_v1alpha4_ExternalRouterIPParam(a.(*ExternalRouterIPParam), b.(*v1alpha4.ExternalRouterIPParam), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.ExternalRouterIPParam)(nil), (*ExternalRouterIPParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ExternalRouterIPParam_To_v1alpha5_ExternalRouterIPParam(a.(*v1alpha4.ExternalRouterIPParam), b.(*ExternalRouterIPParam), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Filter)(nil), (*v1alpha4.Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_Filter_To_v1alpha4_Filter(a.(*Filter), b.(*v1alpha4.Filter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Filter)(nil), (*Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Filter_To_v1alpha5_Filter(a.(*v1alpha4.Filter), b.(*Filter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FixedIP)(nil), (*v1alpha4.FixedIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_FixedIP_To_v1alpha4_FixedIP(a.(*FixedIP), b.(*v1alpha4.FixedIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.FixedIP)(nil), (*FixedIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_FixedIP_To_v1alpha5_FixedIP(a.(*v1alpha4.FixedIP), b.(*FixedIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Instance)(nil), (*v1alpha4.Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_Instance_To_v1alpha4_Instance(a.(*Instance), b.(*v1alpha4.Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Instance)(nil), (*Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Instance_To_v1alpha5_Instance(a.(*v1alpha4.Instance), b.(*Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LoadBalancer)(nil), (*v1alpha4.LoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_LoadBalancer_To_v1alpha4_LoadBalancer(a.(*LoadBalancer), b.(*v1alpha4.LoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.LoadBalancer)(nil), (*LoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_LoadBalancer_To_v1alpha5_LoadBalancer(a.(*v1alpha4.LoadBalancer), b.(*LoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Network)(nil), (*v1alpha4.Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_Network_To_v1alpha4_Network(a.(*Network), b.(*v1alpha4.Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Network)(nil), (*Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Network_To_v1alpha5_Network(a.(*v1alpha4.Network), b.(*Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkParam)(nil), (*v1alpha4.NetworkParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_NetworkParam_To_v1alpha4_NetworkParam(a.(*NetworkParam), b.(*v1alpha4.NetworkParam), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.NetworkParam)(nil), (*NetworkParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkParam_To_v1alpha5_NetworkParam(a.(*v1alpha4.NetworkParam), b.(*NetworkParam), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackCluster)(nil), (*v1alpha4.OpenStackCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackCluster_To_v1alpha4_OpenStackCluster(a.(*OpenStackCluster), b.(*v1alpha4.OpenStackCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackCluster)(nil), (*OpenStackCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackCluster_To_v1alpha5_OpenStackCluster(a.(*v1alpha4.OpenStackCluster), b.(*OpenStackCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackClusterList)(nil), (*v1alpha4.OpenStackClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackClusterList_To_v1alpha4_OpenStackClusterList(a.(*OpenStackClusterList), b.(*v1alpha4.OpenStackClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackClusterList)(nil), (*OpenStackClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackClusterList_To_v1alpha5_OpenStackClusterList(a.(*v1alpha4.OpenStackClusterList), b.(*OpenStackClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackClusterSpec)(nil), (*v1alpha4.OpenStackClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackClusterSpec_To_v1alpha4_OpenStackClusterSpec(a.(*OpenStackClusterSpec), b.(*v1alpha4.OpenStackClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackClusterSpec)(nil), (*OpenStackClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(a.(*v1alpha4.OpenStackClusterSpec), b.(*OpenStackClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackClusterStatus)(nil), (*v1alpha4.OpenStackClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackClusterStatus_To_v1alpha4_OpenStackClusterStatus(a.(*OpenStackClusterStatus), b.(*v1alpha4.OpenStackClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackClusterStatus)(nil), (*OpenStackClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackClusterStatus_To_v1alpha5_OpenStackClusterStatus(a.(*v1alpha4.OpenStackClusterStatus), b.(*OpenStackClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackClusterTemplate)(nil), (*v1alpha4.OpenStackClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackClusterTemplate_To_v1alpha4_OpenStackClusterTemplate(a.(*OpenStackClusterTemplate), b.(*v1alpha4.OpenStackClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackClusterTemplate)(nil), (*OpenStackClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackClusterTemplate_To_v1alpha5_OpenStackClusterTemplate(a.(*v1alpha4.OpenStackClusterTemplate), b.(*OpenStackClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackClusterTemplateList)(nil), (*v1alpha4.OpenStackClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackClusterTemplateList_To_v1alpha4_OpenStackClusterTemplateList(a.(*OpenStackClusterTemplateList), b.(*v1alpha4.OpenStackClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackClusterTemplateList)(nil), (*OpenStackClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackClusterTemplateList_To_v1alpha5_OpenStackClusterTemplateList(a.(*v1alpha4.OpenStackClusterTemplateList), b.(*OpenStackClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackClusterTemplateResource)(nil), (*v1alpha4.OpenStackClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackClusterTemplateResource_To_v1alpha4_OpenStackClusterTemplateResource(a.(*OpenStackClusterTemplateResource), b.(*v1alpha4.OpenStackClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackClusterTemplateResource)(nil), (*OpenStackClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackClusterTemplateResource_To_v1alpha5_OpenStackClusterTemplateResource(a.(*v1alpha4.OpenStackClusterTemplateResource), b.(*OpenStackClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackClusterTemplateSpec)(nil), (*v1alpha4.OpenStackClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackClusterTemplateSpec_To_v1alpha4_OpenStackClusterTemplateSpec(a.(*OpenStackClusterTemplateSpec), b.(*v1alpha4.OpenStackClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackClusterTemplateSpec)(nil), (*OpenStackClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackClusterTemplateSpec_To_v1alpha5_OpenStackClusterTemplateSpec(a.(*v1alpha4.OpenStackClusterTemplateSpec), b.(*OpenStackClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackIdentityReference)(nil), (*v1alpha4.OpenStackIdentityReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackIdentityReference_To_v1alpha4_OpenStackIdentityReference(a.(*OpenStackIdentityReference), b.(*v1alpha4.OpenStackIdentityReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackIdentityReference)(nil), (*OpenStackIdentityReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackIdentityReference_To_v1alpha5_OpenStackIdentityReference(a.(*v1alpha4.OpenStackIdentityReference), b.(*OpenStackIdentityReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachine)(nil), (*v1alpha4.OpenStackMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachine_To_v1alpha4_OpenStackMachine(a.(*OpenStackMachine), b.(*v1alpha4.OpenStackMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachine)(nil), (*OpenStackMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachine_To_v1alpha5_OpenStackMachine(a.(*v1alpha4.OpenStackMachine), b.(*OpenStackMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachineList)(nil), (*v1alpha4.OpenStackMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachineList_To_v1alpha4_OpenStackMachineList(a.(*OpenStackMachineList), b.(*v1alpha4.OpenStackMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachineList)(nil), (*OpenStackMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachineList_To_v1alpha5_OpenStackMachineList(a.(*v1alpha4.OpenStackMachineList), b.(*OpenStackMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachineSpec)(nil), (*v1alpha4.OpenStackMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec(a.(*OpenStackMachineSpec), b.(*v1alpha4.OpenStackMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachineSpec)(nil), (*OpenStackMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec(a.(*v1alpha4.OpenStackMachineSpec), b.(*OpenStackMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachineStatus)(nil), (*v1alpha4.OpenStackMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachineStatus_To_v1alpha4_OpenStackMachineStatus(a.(*OpenStackMachineStatus), b.(*v1alpha4.OpenStackMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachineStatus)(nil), (*OpenStackMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachineStatus_To_v1alpha5_OpenStackMachineStatus(a.(*v1alpha4.OpenStackMachineStatus), b.(*OpenStackMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachineTemplate)(nil), (*v1alpha4.OpenStackMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachineTemplate_To_v1alpha4_OpenStackMachineTemplate(a.(*OpenStackMachineTemplate), b.(*v1alpha4.OpenStackMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachineTemplate)(nil), (*OpenStackMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachineTemplate_To_v1alpha5_OpenStackMachineTemplate(a.(*v1alpha4.OpenStackMachineTemplate), b.(*OpenStackMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachineTemplateList)(nil), (*v1alpha4.OpenStackMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachineTemplateList_To_v1alpha4_OpenStackMachineTemplateList(a.(*OpenStackMachineTemplateList), b.(*v1alpha4.OpenStackMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachineTemplateList)(nil), (*OpenStackMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachineTemplateList_To_v1alpha5_OpenStackMachineTemplateList(a.(*v1alpha4.OpenStackMachineTemplateList), b.(*OpenStackMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachineTemplateResource)(nil), (*v1alpha4.OpenStackMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachineTemplateResource_To_v1alpha4_OpenStackMachineTemplateResource(a.(*OpenStackMachineTemplateResource), b.(*v1alpha4.OpenStackMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachineTemplateResource)(nil), (*OpenStackMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachineTemplateResource_To_v1alpha5_OpenStackMachineTemplateResource(a.(*v1alpha4.OpenStackMachineTemplateResource), b.(*OpenStackMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenStackMachineTemplateSpec)(nil), (*v1alpha4.OpenStackMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_OpenStackMachineTemplateSpec_To_v1alpha4_OpenStackMachineTemplateSpec(a.(*OpenStackMachineTemplateSpec), b.(*v1alpha4.OpenStackMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.OpenStackMachineTemplateSpec)(nil), (*OpenStackMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_OpenStackMachineTemplateSpec_To_v1alpha5_OpenStackMachineTemplateSpec(a.(*v1alpha4.OpenStackMachineTemplateSpec), b.(*OpenStackMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortOpts)(nil), (*v1alpha4.PortOpts)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_PortOpts_To_v1alpha4_PortOpts(a.(*PortOpts), b.(*v1alpha4.PortOpts), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.PortOpts)(nil), (*PortOpts)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_PortOpts_To_v1alpha5_PortOpts(a.(*v1alpha4.PortOpts), b.(*PortOpts), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootVolume)(nil), (*v1alpha4.RootVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_RootVolume_To_v1alpha4_RootVolume(a.(*RootVolume), b.(*v1alpha4.RootVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.RootVolume)(nil), (*RootVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_RootVolume_To_v1alpha5_RootVolume(a.(*v1alpha4.RootVolume), b.(*RootVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Router)(nil), (*v1alpha4.Router)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_Router_To_v1alpha4_Router(a.(*Router), b.(*v1alpha4.Router), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Router)(nil), (*Router)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Router_To_v1alpha5_Router(a.(*v1alpha4.Router), b.(*Router), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroup)(nil), (*v1alpha4.SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_SecurityGroup_To_v1alpha4_SecurityGroup(a.(*SecurityGroup), b.(*v1alpha4.SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SecurityGroup)(nil), (*SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SecurityGroup_To_v1alpha5_SecurityGroup(a.(*v1alpha4.SecurityGroup), b.(*SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupFilter)(nil), (*v1alpha4.SecurityGroupFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_SecurityGroupFilter_To_v1alpha4_SecurityGroupFilter(a.(*SecurityGroupFilter), b.(*v1alpha4.SecurityGroupFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SecurityGroupFilter)(nil), (*SecurityGroupFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SecurityGroupFilter_To_v1alpha5_SecurityGroupFilter(a.(*v1alpha4.SecurityGroupFilter), b.(*SecurityGroupFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupParam)(nil), (*v1alpha4.SecurityGroupParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_SecurityGroupParam_To_v1alpha4_SecurityGroupParam(a.(*SecurityGroupParam), b.(*v1alpha4.SecurityGroupParam), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SecurityGroupParam)(nil), (*SecurityGroupParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SecurityGroupParam_To_v1alpha5_SecurityGroupParam(a.(*v1alpha4.SecurityGroupParam), b.(*SecurityGroupParam), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupRule)(nil), (*v1alpha4.SecurityGroupRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_SecurityGroupRule_To_v1alpha4_SecurityGroupRule(a.(*SecurityGroupRule), b.(*v1alpha4.SecurityGroupRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SecurityGroupRule)(nil), (*SecurityGroupRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SecurityGroupRule_To_v1alpha5_SecurityGroupRule(a.(*v1alpha4.SecurityGroupRule), b.(*SecurityGroupRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subnet)(nil), (*v1alpha4.Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_Subnet_To_v1alpha4_Subnet(a.(*Subnet), b.(*v1alpha4.Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Subnet)(nil), (*Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Subnet_To_v1alpha5_Subnet(a.(*v1alpha4.Subnet), b.(*Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetFilter)(nil), (*v1alpha4.SubnetFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_SubnetFilter_To_v1alpha4_SubnetFilter(a.(*SubnetFilter), b.(*v1alpha4.SubnetFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SubnetFilter)(nil), (*SubnetFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SubnetFilter_To_v1alpha5_SubnetFilter(a.(*v1alpha4.SubnetFilter), b.(*SubnetFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetParam)(nil), (*v1alpha4.SubnetParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha5_SubnetParam_To_v1alpha4_SubnetParam(a.(*SubnetParam), b.(*v1alpha4.SubnetParam), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.SubnetParam)(nil), (*SubnetParam)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SubnetParam_To_v1alpha5_SubnetParam(a.(*v1alpha4.SubnetParam), b.(*SubnetParam), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha5_AddressPair_To_v1alpha4_AddressPair(in *AddressPair, out *v1alpha4.AddressPair, s conversion.Scope) error {
	out.IPAddress = in.IPAddress
	out.MACAddress = in.MACAddress
	return nil
}

// Convert_v1alpha5_AddressPair_To_v1alpha4_AddressPair is an autogenerated conversion function.
func Convert_v1alpha5_AddressPair_To_v1alpha4_AddressPair(in *AddressPair, out *v1alpha4.AddressPair, s conversion.Scope) error {
	return autoConvert_v1alpha5_AddressPair_To_v1alpha4_AddressPair(in, out, s)
}

func autoConvert_v1alpha4_AddressPair_To_v1alpha5_AddressPair(in *v1alpha4.AddressPair, out *AddressPair, s conversion.Scope) error {
	out.IPAddress = in.IPAddress
	out.MACAddress = in.MACAddress
	return nil
}

// Convert_v1alpha4_AddressPair_To_v1alpha5_AddressPair is an autogenerated conversion function.
func Convert_v1alpha4_AddressPair_To_v1alpha5_AddressPair(in *v1alpha4.AddressPair, out *AddressPair, s conversion.Scope) error {
	return autoConvert_v1alpha4_AddressPair_To_v1alpha5_AddressPair(in, out, s)
}

func autoConvert_v1alpha5_Bastion_To_v1alpha4_Bastion(in *Bastion, out *v1alpha4.Bastion, s conversion.Scope) error {
	out.Enabled = in.Enabled
	if err := Convert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec(&in.Instance, &out.Instance, s); err != nil {
		return err
	}
	out.AvailabilityZone = in.AvailabilityZone
	return nil
}

// Convert_v1alpha5_Bastion_To_v1alpha4_Bastion is an autogenerated conversion function.
func Convert_v1alpha5_Bastion_To_v1alpha4_Bastion(in *Bastion, out *v1alpha4.Bastion, s conversion.Scope) error {
	return autoConvert_v1alpha5_Bastion_To_v1alpha4_Bastion(in, out, s)
}

func autoConvert_v1alpha4_Bastion_To_v1alpha5_Bastion(in *v1alpha4.Bastion, out *Bastion, s conversion.Scope) error {
	out.Enabled = in.Enabled
	if err := Convert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec(&in.Instance, &out.Instance, s); err != nil {
		return err
	}
	out.AvailabilityZone = in.AvailabilityZone
	return nil
}

// Convert_v1alpha4_Bastion_To_v1alpha5_Bastion is an autogenerated conversion function.
func Convert_v1alpha4_Bastion_To_v1alpha5_Bastion(in *v1alpha4.Bastion, out *Bastion, s conversion.Scope) error {
	return autoConvert_v1alpha4_Bastion_To_v1alpha5_Bastion(in, out, s)
}

func autoConvert_v1alpha5_ExternalRouterIPParam_To_v1alpha4_ExternalRouterIPParam(in *ExternalRouterIPParam, out *v1alpha4.ExternalRouterIPParam, s conversion.Scope) error {
	out.FixedIP = in.FixedIP
	if err := Convert_v1alpha5_SubnetParam_To_v1alpha4_SubnetParam(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_ExternalRouterIPParam_To_v1alpha4_ExternalRouterIPParam is an autogenerated conversion function.
func Convert_v1alpha5_ExternalRouterIPParam_To_v1alpha4_ExternalRouterIPParam(in *ExternalRouterIPParam, out *v1alpha4.ExternalRouterIPParam, s conversion.Scope) error {
	return autoConvert_v1alpha5_ExternalRouterIPParam_To_v1alpha4_ExternalRouterIPParam(in, out, s)
}

func autoConvert_v1alpha4_ExternalRouterIPParam_To_v1alpha5_ExternalRouterIPParam(in *v1alpha4.ExternalRouterIPParam, out *ExternalRouterIPParam, s conversion.Scope) error {
	out.FixedIP = in.FixedIP
	if err := Convert_v1alpha4_SubnetParam_To_v1alpha5_SubnetParam(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_ExternalRouterIPParam_To_v1alpha5_ExternalRouterIPParam is an autogenerated conversion function.
func Convert_v1alpha4_ExternalRouterIPParam_To_v1alpha5_ExternalRouterIPParam(in *v1alpha4.ExternalRouterIPParam, out *ExternalRouterIPParam, s conversion.Scope) error {
	return autoConvert_v1alpha4_ExternalRouterIPParam_To_v1alpha5_ExternalRouterIPParam(in, out, s)
}

func autoConvert_v1alpha5_Filter_To_v1alpha4_Filter(in *Filter, out *v1alpha4.Filter, s conversion.Scope) error {
	out.Status = in.Status
	out.Name = in.Name
	out.Description = in.Description
	out.AdminStateUp = (*bool)(unsafe.Pointer(in.AdminStateUp))
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.Shared = (*bool)(unsafe.Pointer(in.Shared))
	out.ID = in.ID
	out.Marker = in.Marker
	out.Limit = in.Limit
	out.SortKey = in.SortKey
	out.SortDir = in.SortDir
	out.Tags = in.Tags
	out.TagsAny = in.TagsAny
	out.NotTags = in.NotTags
	out.NotTagsAny = in.NotTagsAny
	return nil
}

// Convert_v1alpha5_Filter_To_v1alpha4_Filter is an autogenerated conversion function.
func Convert_v1alpha5_Filter_To_v1alpha4_Filter(in *Filter, out *v1alpha4.Filter, s conversion.Scope) error {
	return autoConvert_v1alpha5_Filter_To_v1alpha4_Filter(in, out, s)
}

func autoConvert_v1alpha4_Filter_To_v1alpha5_Filter(in *v1alpha4.Filter, out *Filter, s conversion.Scope) error {
	out.Status = in.Status
	out.Name = in.Name
	out.Description = in.Description
	out.AdminStateUp = (*bool)(unsafe.Pointer(in.AdminStateUp))
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.Shared = (*bool)(unsafe.Pointer(in.Shared))
	out.ID = in.ID
	out.Marker = in.Marker
	out.Limit = in.Limit
	out.SortKey = in.SortKey
	out.SortDir = in.SortDir
	out.Tags = in.Tags
	out.TagsAny = in.TagsAny
	out.NotTags = in.NotTags
	out.NotTagsAny = in.NotTagsAny
	return nil
}

// Convert_v1alpha4_Filter_To_v1alpha5_Filter is an autogenerated conversion function.
func Convert_v1alpha4_Filter_To_v1alpha5_Filter(in *v1alpha4.Filter, out *Filter, s conversion.Scope) error {
	return autoConvert_v1alpha4_Filter_To_v1alpha5_Filter(in, out, s)
}

func autoConvert_v1alpha5_FixedIP_To_v1alpha4_FixedIP(in *FixedIP, out *v1alpha4.FixedIP, s conversion.Scope) error {
	out.SubnetID = in.SubnetID
	out.IPAddress = in.IPAddress
	return nil
}

// Convert_v1alpha5_FixedIP_To_v1alpha4_FixedIP is an autogenerated conversion function.
func Convert_v1alpha5_FixedIP_To_v1alpha4_FixedIP(in *FixedIP, out *v1alpha4.FixedIP, s conversion.Scope) error {
	return autoConvert_v1alpha5_FixedIP_To_v1alpha4_FixedIP(in, out, s)
}

func autoConvert_v1alpha4_FixedIP_To_v1alpha5_FixedIP(in *v1alpha4.FixedIP, out *FixedIP, s conversion.Scope) error {
	out.SubnetID = in.SubnetID
	out.IPAddress = in.IPAddress
	return nil
}

// Convert_v1alpha4_FixedIP_To_v1alpha5_FixedIP is an autogenerated conversion function.
func Convert_v1alpha4_FixedIP_To_v1alpha5_FixedIP(in *v1alpha4.FixedIP, out *FixedIP, s conversion.Scope) error {
	return autoConvert_v1alpha4_FixedIP_To_v1alpha5_FixedIP(in, out, s)
}

func autoConvert_v1alpha5_Instance_To_v1alpha4_Instance(in *Instance, out *v1alpha4.Instance, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.Trunk = in.Trunk
	out.FailureDomain = in.FailureDomain
	out.SecurityGroups = (*[]string)(unsafe.Pointer(in.SecurityGroups))
	out.Networks = (*[]v1alpha4.Network)(unsafe.Pointer(in.Networks))
	out.Subnet = in.Subnet
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Image = in.Image
	out.Flavor = in.Flavor
	out.SSHKeyName = in.SSHKeyName
	out.UserData = in.UserData
	out.Metadata = *(*map[string]string)(unsafe.Pointer(&in.Metadata))
	out.ConfigDrive = (*bool)(unsafe.Pointer(in.ConfigDrive))
	out.RootVolume = (*v1alpha4.RootVolume)(unsafe.Pointer(in.RootVolume))
	out.ServerGroupID = in.ServerGroupID
	out.State = v1alpha4.InstanceState(in.State)
	out.IP = in.IP
	out.FloatingIP = in.FloatingIP
	return nil
}

// Convert_v1alpha5_Instance_To_v1alpha4_Instance is an autogenerated conversion function.
func Convert_v1alpha5_Instance_To_v1alpha4_Instance(in *Instance, out *v1alpha4.Instance, s conversion.Scope) error {
	return autoConvert_v1alpha5_Instance_To_v1alpha4_Instance(in, out, s)
}

func autoConvert_v1alpha4_Instance_To_v1alpha5_Instance(in *v1alpha4.Instance, out *Instance, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.Trunk = in.Trunk
	out.FailureDomain = in.FailureDomain
	out.SecurityGroups = (*[]string)(unsafe.Pointer(in.SecurityGroups))
	out.Networks = (*[]Network)(unsafe.Pointer(in.Networks))
	out.Subnet = in.Subnet
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Image = in.Image
	out.Flavor = in.Flavor
	out.SSHKeyName = in.SSHKeyName
	out.UserData = in.UserData
	out.Metadata = *(*map[string]string)(unsafe.Pointer(&in.Metadata))
	out.ConfigDrive = (*bool)(unsafe.Pointer(in.ConfigDrive))
	out.RootVolume = (*RootVolume)(unsafe.Pointer(in.RootVolume))
	out.ServerGroupID = in.ServerGroupID
	out.State = InstanceState(in.State)
	out.IP = in.IP
	out.FloatingIP = in.FloatingIP
	return nil
}

// Convert_v1alpha4_Instance_To_v1alpha5_Instance is an autogenerated conversion function.
func Convert_v1alpha4_Instance_To_v1alpha5_Instance(in *v1alpha4.Instance, out *Instance, s conversion.Scope) error {
	return autoConvert_v1alpha4_Instance_To_v1alpha5_Instance(in, out, s)
}

func autoConvert_v1alpha5_LoadBalancer_To_v1alpha4_LoadBalancer(in *LoadBalancer, out *v1alpha4.LoadBalancer, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.IP = in.IP
	out.InternalIP = in.InternalIP
	return nil
}

// Convert_v1alpha5_LoadBalancer_To_v1alpha4_LoadBalancer is an autogenerated conversion function.
func Convert_v1alpha5_LoadBalancer_To_v1alpha4_LoadBalancer(in *LoadBalancer, out *v1alpha4.LoadBalancer, s conversion.Scope) error {
	return autoConvert_v1alpha5_LoadBalancer_To_v1alpha4_LoadBalancer(in, out, s)
}

func autoConvert_v1alpha4_LoadBalancer_To_v1alpha5_LoadBalancer(in *v1alpha4.LoadBalancer, out *LoadBalancer, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.IP = in.IP
	out.InternalIP = in.InternalIP
	return nil
}

// Convert_v1alpha4_LoadBalancer_To_v1alpha5_LoadBalancer is an autogenerated conversion function.
func Convert_v1alpha4_LoadBalancer_To_v1alpha5_LoadBalancer(in *v1alpha4.LoadBalancer, out *LoadBalancer, s conversion.Scope) error {
	return autoConvert_v1alpha4_LoadBalancer_To_v1alpha5_LoadBalancer(in, out, s)
}

func autoConvert_v1alpha5_Network_To_v1alpha4_Network(in *Network, out *v1alpha4.Network, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Subnet = (*v1alpha4.Subnet)(unsafe.Pointer(in.Subnet))
	out.PortOpts = (*v1alpha4.PortOpts)(unsafe.Pointer(in.PortOpts))
	out.Router = (*v1alpha4.Router)(unsafe.Pointer(in.Router))
	out.APIServerLoadBalancer = (*v1alpha4.LoadBalancer)(unsafe.Pointer(in.APIServerLoadBalancer))
	return nil
}

// Convert_v1alpha5_Network_To_v1alpha4_Network is an autogenerated conversion function.
func Convert_v1alpha5_Network_To_v1alpha4_Network(in *Network, out *v1alpha4.Network, s conversion.Scope) error {
	return autoConvert_v1alpha5_Network_To_v1alpha4_Network(in, out, s)
}

func autoConvert_v1alpha4_Network_To_v1alpha5_Network(in *v1alpha4.Network, out *Network, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Subnet = (*Subnet)(unsafe.Pointer(in.Subnet))
	out.PortOpts = (*PortOpts)(unsafe.Pointer(in.PortOpts))
	out.Router = (*Router)(unsafe.Pointer(in.Router))
	out.APIServerLoadBalancer = (*LoadBalancer)(unsafe.Pointer(in.APIServerLoadBalancer))
	return nil
}

// Convert_v1alpha4_Network_To_v1alpha5_Network is an autogenerated conversion function.
func Convert_v1alpha4_Network_To_v1alpha5_Network(in *v1alpha4.Network, out *Network, s conversion.Scope) error {
	return autoConvert_v1alpha4_Network_To_v1alpha5_Network(in, out, s)
}

func autoConvert_v1alpha5_NetworkParam_To_v1alpha4_NetworkParam(in *NetworkParam, out *v1alpha4.NetworkParam, s conversion.Scope) error {
	out.UUID = in.UUID
	out.FixedIP = in.FixedIP
	if err := Convert_v1alpha5_Filter_To_v1alpha4_Filter(&in.Filter, &out.Filter, s); err != nil {
		return err
	}
	out.Subnets = *(*[]v1alpha4.SubnetParam)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1alpha5_NetworkParam_To_v1alpha4_NetworkParam is an autogenerated conversion function.
func Convert_v1alpha5_NetworkParam_To_v1alpha4_NetworkParam(in *NetworkParam, out *v1alpha4.NetworkParam, s conversion.Scope) error {
	return autoConvert_v1alpha5_NetworkParam_To_v1alpha4_NetworkParam(in, out, s)
}

func autoConvert_v1alpha4_NetworkParam_To_v1alpha5_NetworkParam(in *v1alpha4.NetworkParam, out *NetworkParam, s conversion.Scope) error {
	out.UUID = in.UUID
	out.FixedIP = in.FixedIP
	if err := Convert_v1alpha4_Filter_To_v1alpha5_Filter(&in.Filter, &out.Filter, s); err != nil {
		return err
	}
	out.Subnets = *(*[]SubnetParam)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1alpha4_NetworkParam_To_v1alpha5_NetworkParam is an autogenerated conversion function.
func Convert_v1alpha4_NetworkParam_To_v1alpha5_NetworkParam(in *v1alpha4.NetworkParam, out *NetworkParam, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkParam_To_v1alpha5_NetworkParam(in, out, s)
}

func autoConvert_v1alpha5_OpenStackCluster_To_v1alpha4_OpenStackCluster(in *OpenStackCluster, out *v1alpha4.OpenStackCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha5_OpenStackClusterSpec_To_v1alpha4_OpenStackClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha5_OpenStackClusterStatus_To_v1alpha4_OpenStackClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackCluster_To_v1alpha4_OpenStackCluster is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackCluster_To_v1alpha4_OpenStackCluster(in *OpenStackCluster, out *v1alpha4.OpenStackCluster, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackCluster_To_v1alpha4_OpenStackCluster(in, out, s)
}

func autoConvert_v1alpha4_OpenStackCluster_To_v1alpha5_OpenStackCluster(in *v1alpha4.OpenStackCluster, out *OpenStackCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OpenStackClusterStatus_To_v1alpha5_OpenStackClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackCluster_To_v1alpha5_OpenStackCluster is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackCluster_To_v1alpha5_OpenStackCluster(in *v1alpha4.OpenStackCluster, out *OpenStackCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackCluster_To_v1alpha5_OpenStackCluster(in, out, s)
}

func autoConvert_v1alpha5_OpenStackClusterList_To_v1alpha4_OpenStackClusterList(in *OpenStackClusterList, out *v1alpha4.OpenStackClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.OpenStackCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha5_OpenStackClusterList_To_v1alpha4_OpenStackClusterList is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackClusterList_To_v1alpha4_OpenStackClusterList(in *OpenStackClusterList, out *v1alpha4.OpenStackClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackClusterList_To_v1alpha4_OpenStackClusterList(in, out, s)
}

func autoConvert_v1alpha4_OpenStackClusterList_To_v1alpha5_OpenStackClusterList(in *v1alpha4.OpenStackClusterList, out *OpenStackClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OpenStackCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_OpenStackClusterList_To_v1alpha5_OpenStackClusterList is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackClusterList_To_v1alpha5_OpenStackClusterList(in *v1alpha4.OpenStackClusterList, out *OpenStackClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackClusterList_To_v1alpha5_OpenStackClusterList(in, out, s)
}

func autoConvert_v1alpha5_OpenStackClusterSpec_To_v1alpha4_OpenStackClusterSpec(in *OpenStackClusterSpec, out *v1alpha4.OpenStackClusterSpec, s conversion.Scope) error {
	out.CloudName = in.CloudName
	out.NodeCIDR = in.NodeCIDR
	if err := Convert_v1alpha5_Filter_To_v1alpha4_Filter(&in.Network, &out.Network, s); err != nil {
		return err
	}
	if err := Convert_v1alpha5_SubnetFilter_To_v1alpha4_SubnetFilter(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	out.DNSNameservers = *(*[]string)(unsafe.Pointer(&in.DNSNameservers))
	out.ExternalRouterIPs = *(*[]v1alpha4.ExternalRouterIPParam)(unsafe.Pointer(&in.ExternalRouterIPs))
	out.ExternalNetworkID = in.ExternalNetworkID
	out.ManagedAPIServerLoadBalancer = in.ManagedAPIServerLoadBalancer
	out.DisableAPIServerFloatingIP = in.DisableAPIServerFloatingIP
	out.APIServerFloatingIP = in.APIServerFloatingIP
	out.APIServerFixedIP = in.APIServerFixedIP
	out.APIServerPort = in.APIServerPort
	out.APIServerLoadBalancerAdditionalPorts = *(*[]int)(unsafe.Pointer(&in.APIServerLoadBalancerAdditionalPorts))
	out.ManagedSecurityGroups = in.ManagedSecurityGroups
	out.AllowAllInClusterTraffic = in.AllowAllInClusterTraffic
	out.DisablePortSecurity = in.DisablePortSecurity
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.ControlPlaneAvailabilityZones = *(*[]string)(unsafe.Pointer(&in.ControlPlaneAvailabilityZones))
	out.Bastion = (*v1alpha4.Bastion)(unsafe.Pointer(in.Bastion))
	// INFO: in.IdentityRef opted out of conversion generation
	return nil
}

// Convert_v1alpha5_OpenStackClusterSpec_To_v1alpha4_OpenStackClusterSpec is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackClusterSpec_To_v1alpha4_OpenStackClusterSpec(in *OpenStackClusterSpec, out *v1alpha4.OpenStackClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackClusterSpec_To_v1alpha4_OpenStackClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(in *v1alpha4.OpenStackClusterSpec, out *OpenStackClusterSpec, s conversion.Scope) error {
	out.CloudName = in.CloudName
	out.NodeCIDR = in.NodeCIDR
	if err := Convert_v1alpha4_Filter_To_v1alpha5_Filter(&in.Network, &out.Network, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_SubnetFilter_To_v1alpha5_SubnetFilter(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	out.DNSNameservers = *(*[]string)(unsafe.Pointer(&in.DNSNameservers))
	out.ExternalRouterIPs = *(*[]ExternalRouterIPParam)(unsafe.Pointer(&in.ExternalRouterIPs))
	out.ExternalNetworkID = in.ExternalNetworkID
	out.ManagedAPIServerLoadBalancer = in.ManagedAPIServerLoadBalancer
	out.DisableAPIServerFloatingIP = in.DisableAPIServerFloatingIP
	out.APIServerFloatingIP = in.APIServerFloatingIP
	out.APIServerFixedIP = in.APIServerFixedIP
	out.APIServerPort = in.APIServerPort
	out.APIServerLoadBalancerAdditionalPorts = *(*[]int)(unsafe.Pointer(&in.APIServerLoadBalancerAdditionalPorts))
	out.ManagedSecurityGroups = in.ManagedSecurityGroups
	out.AllowAllInClusterTraffic = in.AllowAllInClusterTraffic
	out.DisablePortSecurity = in.DisablePortSecurity
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.ControlPlaneAvailabilityZones = *(*[]string)(unsafe.Pointer(&in.ControlPlaneAvailabilityZones))
	out.Bastion = (*Bastion)(unsafe.Pointer(in.Bastion))
	// INFO: in.IdentityRef opted out of conversion generation
	return nil
}

// Convert_v1alpha4_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(in *v1alpha4.OpenStackClusterSpec, out *OpenStackClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(in, out, s)
}

func autoConvert_v1alpha5_OpenStackClusterStatus_To_v1alpha4_OpenStackClusterStatus(in *OpenStackClusterStatus, out *v1alpha4.OpenStackClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Network = (*v1alpha4.Network)(unsafe.Pointer(in.Network))
	out.ExternalNetwork = (*v1alpha4.Network)(unsafe.Pointer(in.ExternalNetwork))
	out.FailureDomains = *(*apiv1alpha4.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	out.ControlPlaneSecurityGroup = (*v1alpha4.SecurityGroup)(unsafe.Pointer(in.ControlPlaneSecurityGroup))
	out.WorkerSecurityGroup = (*v1alpha4.SecurityGroup)(unsafe.Pointer(in.WorkerSecurityGroup))
	out.BastionSecurityGroup = (*v1alpha4.SecurityGroup)(unsafe.Pointer(in.BastionSecurityGroup))
	out.Bastion = (*v1alpha4.Instance)(unsafe.Pointer(in.Bastion))
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha5_OpenStackClusterStatus_To_v1alpha4_OpenStackClusterStatus is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackClusterStatus_To_v1alpha4_OpenStackClusterStatus(in *OpenStackClusterStatus, out *v1alpha4.OpenStackClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackClusterStatus_To_v1alpha4_OpenStackClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_OpenStackClusterStatus_To_v1alpha5_OpenStackClusterStatus(in *v1alpha4.OpenStackClusterStatus, out *OpenStackClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Network = (*Network)(unsafe.Pointer(in.Network))
	out.ExternalNetwork = (*Network)(unsafe.Pointer(in.ExternalNetwork))
	out.FailureDomains = *(*apiv1alpha4.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	out.ControlPlaneSecurityGroup = (*SecurityGroup)(unsafe.Pointer(in.ControlPlaneSecurityGroup))
	out.WorkerSecurityGroup = (*SecurityGroup)(unsafe.Pointer(in.WorkerSecurityGroup))
	out.BastionSecurityGroup = (*SecurityGroup)(unsafe.Pointer(in.BastionSecurityGroup))
	out.Bastion = (*Instance)(unsafe.Pointer(in.Bastion))
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha4_OpenStackClusterStatus_To_v1alpha5_OpenStackClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackClusterStatus_To_v1alpha5_OpenStackClusterStatus(in *v1alpha4.OpenStackClusterStatus, out *OpenStackClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackClusterStatus_To_v1alpha5_OpenStackClusterStatus(in, out, s)
}

func autoConvert_v1alpha5_OpenStackClusterTemplate_To_v1alpha4_OpenStackClusterTemplate(in *OpenStackClusterTemplate, out *v1alpha4.OpenStackClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha5_OpenStackClusterTemplateSpec_To_v1alpha4_OpenStackClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackClusterTemplate_To_v1alpha4_OpenStackClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackClusterTemplate_To_v1alpha4_OpenStackClusterTemplate(in *OpenStackClusterTemplate, out *v1alpha4.OpenStackClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackClusterTemplate_To_v1alpha4_OpenStackClusterTemplate(in, out, s)
}

func autoConvert_v1alpha4_OpenStackClusterTemplate_To_v1alpha5_OpenStackClusterTemplate(in *v1alpha4.OpenStackClusterTemplate, out *OpenStackClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_OpenStackClusterTemplateSpec_To_v1alpha5_OpenStackClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackClusterTemplate_To_v1alpha5_OpenStackClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackClusterTemplate_To_v1alpha5_OpenStackClusterTemplate(in *v1alpha4.OpenStackClusterTemplate, out *OpenStackClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackClusterTemplate_To_v1alpha5_OpenStackClusterTemplate(in, out, s)
}

func autoConvert_v1alpha5_OpenStackClusterTemplateList_To_v1alpha4_OpenStackClusterTemplateList(in *OpenStackClusterTemplateList, out *v1alpha4.OpenStackClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.OpenStackClusterTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha5_OpenStackClusterTemplateList_To_v1alpha4_OpenStackClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackClusterTemplateList_To_v1alpha4_OpenStackClusterTemplateList(in *OpenStackClusterTemplateList, out *v1alpha4.OpenStackClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackClusterTemplateList_To_v1alpha4_OpenStackClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha4_OpenStackClusterTemplateList_To_v1alpha5_OpenStackClusterTemplateList(in *v1alpha4.OpenStackClusterTemplateList, out *OpenStackClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OpenStackClusterTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_OpenStackClusterTemplateList_To_v1alpha5_OpenStackClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackClusterTemplateList_To_v1alpha5_OpenStackClusterTemplateList(in *v1alpha4.OpenStackClusterTemplateList, out *OpenStackClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackClusterTemplateList_To_v1alpha5_OpenStackClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha5_OpenStackClusterTemplateResource_To_v1alpha4_OpenStackClusterTemplateResource(in *OpenStackClusterTemplateResource, out *v1alpha4.OpenStackClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha5_OpenStackClusterSpec_To_v1alpha4_OpenStackClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackClusterTemplateResource_To_v1alpha4_OpenStackClusterTemplateResource is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackClusterTemplateResource_To_v1alpha4_OpenStackClusterTemplateResource(in *OpenStackClusterTemplateResource, out *v1alpha4.OpenStackClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackClusterTemplateResource_To_v1alpha4_OpenStackClusterTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_OpenStackClusterTemplateResource_To_v1alpha5_OpenStackClusterTemplateResource(in *v1alpha4.OpenStackClusterTemplateResource, out *OpenStackClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_OpenStackClusterSpec_To_v1alpha5_OpenStackClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackClusterTemplateResource_To_v1alpha5_OpenStackClusterTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackClusterTemplateResource_To_v1alpha5_OpenStackClusterTemplateResource(in *v1alpha4.OpenStackClusterTemplateResource, out *OpenStackClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackClusterTemplateResource_To_v1alpha5_OpenStackClusterTemplateResource(in, out, s)
}

func autoConvert_v1alpha5_OpenStackClusterTemplateSpec_To_v1alpha4_OpenStackClusterTemplateSpec(in *OpenStackClusterTemplateSpec, out *v1alpha4.OpenStackClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha5_OpenStackClusterTemplateResource_To_v1alpha4_OpenStackClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackClusterTemplateSpec_To_v1alpha4_OpenStackClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackClusterTemplateSpec_To_v1alpha4_OpenStackClusterTemplateSpec(in *OpenStackClusterTemplateSpec, out *v1alpha4.OpenStackClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackClusterTemplateSpec_To_v1alpha4_OpenStackClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_OpenStackClusterTemplateSpec_To_v1alpha5_OpenStackClusterTemplateSpec(in *v1alpha4.OpenStackClusterTemplateSpec, out *OpenStackClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_OpenStackClusterTemplateResource_To_v1alpha5_OpenStackClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackClusterTemplateSpec_To_v1alpha5_OpenStackClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackClusterTemplateSpec_To_v1alpha5_OpenStackClusterTemplateSpec(in *v1alpha4.OpenStackClusterTemplateSpec, out *OpenStackClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackClusterTemplateSpec_To_v1alpha5_OpenStackClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha5_OpenStackIdentityReference_To_v1alpha4_OpenStackIdentityReference(in *OpenStackIdentityReference, out *v1alpha4.OpenStackIdentityReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_v1alpha5_OpenStackIdentityReference_To_v1alpha4_OpenStackIdentityReference is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackIdentityReference_To_v1alpha4_OpenStackIdentityReference(in *OpenStackIdentityReference, out *v1alpha4.OpenStackIdentityReference, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackIdentityReference_To_v1alpha4_OpenStackIdentityReference(in, out, s)
}

func autoConvert_v1alpha4_OpenStackIdentityReference_To_v1alpha5_OpenStackIdentityReference(in *v1alpha4.OpenStackIdentityReference, out *OpenStackIdentityReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_v1alpha4_OpenStackIdentityReference_To_v1alpha5_OpenStackIdentityReference is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackIdentityReference_To_v1alpha5_OpenStackIdentityReference(in *v1alpha4.OpenStackIdentityReference, out *OpenStackIdentityReference, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackIdentityReference_To_v1alpha5_OpenStackIdentityReference(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachine_To_v1alpha4_OpenStackMachine(in *OpenStackMachine, out *v1alpha4.OpenStackMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha5_OpenStackMachineStatus_To_v1alpha4_OpenStackMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackMachine_To_v1alpha4_OpenStackMachine is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachine_To_v1alpha4_OpenStackMachine(in *OpenStackMachine, out *v1alpha4.OpenStackMachine, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachine_To_v1alpha4_OpenStackMachine(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachine_To_v1alpha5_OpenStackMachine(in *v1alpha4.OpenStackMachine, out *OpenStackMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_OpenStackMachineStatus_To_v1alpha5_OpenStackMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackMachine_To_v1alpha5_OpenStackMachine is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachine_To_v1alpha5_OpenStackMachine(in *v1alpha4.OpenStackMachine, out *OpenStackMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachine_To_v1alpha5_OpenStackMachine(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachineList_To_v1alpha4_OpenStackMachineList(in *OpenStackMachineList, out *v1alpha4.OpenStackMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.OpenStackMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha5_OpenStackMachineList_To_v1alpha4_OpenStackMachineList is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachineList_To_v1alpha4_OpenStackMachineList(in *OpenStackMachineList, out *v1alpha4.OpenStackMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachineList_To_v1alpha4_OpenStackMachineList(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachineList_To_v1alpha5_OpenStackMachineList(in *v1alpha4.OpenStackMachineList, out *OpenStackMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OpenStackMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_OpenStackMachineList_To_v1alpha5_OpenStackMachineList is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachineList_To_v1alpha5_OpenStackMachineList(in *v1alpha4.OpenStackMachineList, out *OpenStackMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachineList_To_v1alpha5_OpenStackMachineList(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec(in *OpenStackMachineSpec, out *v1alpha4.OpenStackMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.InstanceID = (*string)(unsafe.Pointer(in.InstanceID))
	out.CloudName = in.CloudName
	out.Flavor = in.Flavor
	out.Image = in.Image
	out.SSHKeyName = in.SSHKeyName
	out.Networks = *(*[]v1alpha4.NetworkParam)(unsafe.Pointer(&in.Networks))
	out.Ports = *(*[]v1alpha4.PortOpts)(unsafe.Pointer(&in.Ports))
	out.Subnet = in.Subnet
	out.FloatingIP = in.FloatingIP
	out.SecurityGroups = *(*[]v1alpha4.SecurityGroupParam)(unsafe.Pointer(&in.SecurityGroups))
	out.Trunk = in.Trunk
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.ServerMetadata = *(*map[string]string)(unsafe.Pointer(&in.ServerMetadata))
	out.ConfigDrive = (*bool)(unsafe.Pointer(in.ConfigDrive))
	out.RootVolume = (*v1alpha4.RootVolume)(unsafe.Pointer(in.RootVolume))
	out.ServerGroupID = in.ServerGroupID
	// INFO: in.IdentityRef opted out of conversion generation
	return nil
}

// Convert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec(in *OpenStackMachineSpec, out *v1alpha4.OpenStackMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec(in *v1alpha4.OpenStackMachineSpec, out *OpenStackMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.InstanceID = (*string)(unsafe.Pointer(in.InstanceID))
	out.CloudName = in.CloudName
	out.Flavor = in.Flavor
	out.Image = in.Image
	out.SSHKeyName = in.SSHKeyName
	out.Networks = *(*[]NetworkParam)(unsafe.Pointer(&in.Networks))
	out.Ports = *(*[]PortOpts)(unsafe.Pointer(&in.Ports))
	out.Subnet = in.Subnet
	out.FloatingIP = in.FloatingIP
	out.SecurityGroups = *(*[]SecurityGroupParam)(unsafe.Pointer(&in.SecurityGroups))
	out.Trunk = in.Trunk
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.ServerMetadata = *(*map[string]string)(unsafe.Pointer(&in.ServerMetadata))
	out.ConfigDrive = (*bool)(unsafe.Pointer(in.ConfigDrive))
	out.RootVolume = (*RootVolume)(unsafe.Pointer(in.RootVolume))
	out.ServerGroupID = in.ServerGroupID
	// INFO: in.IdentityRef opted out of conversion generation
	return nil
}

// Convert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec(in *v1alpha4.OpenStackMachineSpec, out *OpenStackMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachineStatus_To_v1alpha4_OpenStackMachineStatus(in *OpenStackMachineStatus, out *v1alpha4.OpenStackMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceState = (*v1alpha4.InstanceState)(unsafe.Pointer(in.InstanceState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha5_OpenStackMachineStatus_To_v1alpha4_OpenStackMachineStatus is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachineStatus_To_v1alpha4_OpenStackMachineStatus(in *OpenStackMachineStatus, out *v1alpha4.OpenStackMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachineStatus_To_v1alpha4_OpenStackMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachineStatus_To_v1alpha5_OpenStackMachineStatus(in *v1alpha4.OpenStackMachineStatus, out *OpenStackMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceState = (*InstanceState)(unsafe.Pointer(in.InstanceState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha4_OpenStackMachineStatus_To_v1alpha5_OpenStackMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachineStatus_To_v1alpha5_OpenStackMachineStatus(in *v1alpha4.OpenStackMachineStatus, out *OpenStackMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachineStatus_To_v1alpha5_OpenStackMachineStatus(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachineTemplate_To_v1alpha4_OpenStackMachineTemplate(in *OpenStackMachineTemplate, out *v1alpha4.OpenStackMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha5_OpenStackMachineTemplateSpec_To_v1alpha4_OpenStackMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackMachineTemplate_To_v1alpha4_OpenStackMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachineTemplate_To_v1alpha4_OpenStackMachineTemplate(in *OpenStackMachineTemplate, out *v1alpha4.OpenStackMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachineTemplate_To_v1alpha4_OpenStackMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachineTemplate_To_v1alpha5_OpenStackMachineTemplate(in *v1alpha4.OpenStackMachineTemplate, out *OpenStackMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_OpenStackMachineTemplateSpec_To_v1alpha5_OpenStackMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackMachineTemplate_To_v1alpha5_OpenStackMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachineTemplate_To_v1alpha5_OpenStackMachineTemplate(in *v1alpha4.OpenStackMachineTemplate, out *OpenStackMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachineTemplate_To_v1alpha5_OpenStackMachineTemplate(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachineTemplateList_To_v1alpha4_OpenStackMachineTemplateList(in *OpenStackMachineTemplateList, out *v1alpha4.OpenStackMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.OpenStackMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha5_OpenStackMachineTemplateList_To_v1alpha4_OpenStackMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachineTemplateList_To_v1alpha4_OpenStackMachineTemplateList(in *OpenStackMachineTemplateList, out *v1alpha4.OpenStackMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachineTemplateList_To_v1alpha4_OpenStackMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachineTemplateList_To_v1alpha5_OpenStackMachineTemplateList(in *v1alpha4.OpenStackMachineTemplateList, out *OpenStackMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OpenStackMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_OpenStackMachineTemplateList_To_v1alpha5_OpenStackMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachineTemplateList_To_v1alpha5_OpenStackMachineTemplateList(in *v1alpha4.OpenStackMachineTemplateList, out *OpenStackMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachineTemplateList_To_v1alpha5_OpenStackMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachineTemplateResource_To_v1alpha4_OpenStackMachineTemplateResource(in *OpenStackMachineTemplateResource, out *v1alpha4.OpenStackMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha5_OpenStackMachineSpec_To_v1alpha4_OpenStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackMachineTemplateResource_To_v1alpha4_OpenStackMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachineTemplateResource_To_v1alpha4_OpenStackMachineTemplateResource(in *OpenStackMachineTemplateResource, out *v1alpha4.OpenStackMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachineTemplateResource_To_v1alpha4_OpenStackMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachineTemplateResource_To_v1alpha5_OpenStackMachineTemplateResource(in *v1alpha4.OpenStackMachineTemplateResource, out *OpenStackMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_OpenStackMachineSpec_To_v1alpha5_OpenStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackMachineTemplateResource_To_v1alpha5_OpenStackMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachineTemplateResource_To_v1alpha5_OpenStackMachineTemplateResource(in *v1alpha4.OpenStackMachineTemplateResource, out *OpenStackMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachineTemplateResource_To_v1alpha5_OpenStackMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha5_OpenStackMachineTemplateSpec_To_v1alpha4_OpenStackMachineTemplateSpec(in *OpenStackMachineTemplateSpec, out *v1alpha4.OpenStackMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha5_OpenStackMachineTemplateResource_To_v1alpha4_OpenStackMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_OpenStackMachineTemplateSpec_To_v1alpha4_OpenStackMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha5_OpenStackMachineTemplateSpec_To_v1alpha4_OpenStackMachineTemplateSpec(in *OpenStackMachineTemplateSpec, out *v1alpha4.OpenStackMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha5_OpenStackMachineTemplateSpec_To_v1alpha4_OpenStackMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_OpenStackMachineTemplateSpec_To_v1alpha5_OpenStackMachineTemplateSpec(in *v1alpha4.OpenStackMachineTemplateSpec, out *OpenStackMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_OpenStackMachineTemplateResource_To_v1alpha5_OpenStackMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_OpenStackMachineTemplateSpec_To_v1alpha5_OpenStackMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_OpenStackMachineTemplateSpec_To_v1alpha5_OpenStackMachineTemplateSpec(in *v1alpha4.OpenStackMachineTemplateSpec, out *OpenStackMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_OpenStackMachineTemplateSpec_To_v1alpha5_OpenStackMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha5_PortOpts_To_v1alpha4_PortOpts(in *PortOpts, out *v1alpha4.PortOpts, s conversion.Scope) error {
	out.NetworkID = in.NetworkID
	out.NameSuffix = in.NameSuffix
	out.Description = in.Description
	out.AdminStateUp = (*bool)(unsafe.Pointer(in.AdminStateUp))
	out.MACAddress = in.MACAddress
	out.FixedIPs = *(*[]v1alpha4.FixedIP)(unsafe.Pointer(&in.FixedIPs))
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.SecurityGroups = (*[]string)(unsafe.Pointer(in.SecurityGroups))
	out.AllowedAddressPairs = *(*[]v1alpha4.AddressPair)(unsafe.Pointer(&in.AllowedAddressPairs))
	out.Trunk = (*bool)(unsafe.Pointer(in.Trunk))
	out.HostID = in.HostID
	out.VNICType = in.VNICType
	out.Profile = *(*map[string]string)(unsafe.Pointer(&in.Profile))
	out.DisablePortSecurity = (*bool)(unsafe.Pointer(in.DisablePortSecurity))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha5_PortOpts_To_v1alpha4_PortOpts is an autogenerated conversion function.
func Convert_v1alpha5_PortOpts_To_v1alpha4_PortOpts(in *PortOpts, out *v1alpha4.PortOpts, s conversion.Scope) error {
	return autoConvert_v1alpha5_PortOpts_To_v1alpha4_PortOpts(in, out, s)
}

func autoConvert_v1alpha4_PortOpts_To_v1alpha5_PortOpts(in *v1alpha4.PortOpts, out *PortOpts, s conversion.Scope) error {
	out.NetworkID = in.NetworkID
	out.NameSuffix = in.NameSuffix
	out.Description = in.Description
	out.AdminStateUp = (*bool)(unsafe.Pointer(in.AdminStateUp))
	out.MACAddress = in.MACAddress
	out.FixedIPs = *(*[]FixedIP)(unsafe.Pointer(&in.FixedIPs))
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.SecurityGroups = (*[]string)(unsafe.Pointer(in.SecurityGroups))
	out.AllowedAddressPairs = *(*[]AddressPair)(unsafe.Pointer(&in.AllowedAddressPairs))
	out.Trunk = (*bool)(unsafe.Pointer(in.Trunk))
	out.HostID = in.HostID
	out.VNICType = in.VNICType
	out.Profile = *(*map[string]string)(unsafe.Pointer(&in.Profile))
	out.DisablePortSecurity = (*bool)(unsafe.Pointer(in.DisablePortSecurity))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha4_PortOpts_To_v1alpha5_PortOpts is an autogenerated conversion function.
func Convert_v1alpha4_PortOpts_To_v1alpha5_PortOpts(in *v1alpha4.PortOpts, out *PortOpts, s conversion.Scope) error {
	return autoConvert_v1alpha4_PortOpts_To_v1alpha5_PortOpts(in, out, s)
}

func autoConvert_v1alpha5_RootVolume_To_v1alpha4_RootVolume(in *RootVolume, out *v1alpha4.RootVolume, s conversion.Scope) error {
	out.SourceType = in.SourceType
	out.SourceUUID = in.SourceUUID
	out.DeviceType = in.DeviceType
	out.Size = in.Size
	return nil
}

// Convert_v1alpha5_RootVolume_To_v1alpha4_RootVolume is an autogenerated conversion function.
func Convert_v1alpha5_RootVolume_To_v1alpha4_RootVolume(in *RootVolume, out *v1alpha4.RootVolume, s conversion.Scope) error {
	return autoConvert_v1alpha5_RootVolume_To_v1alpha4_RootVolume(in, out, s)
}

func autoConvert_v1alpha4_RootVolume_To_v1alpha5_RootVolume(in *v1alpha4.RootVolume, out *RootVolume, s conversion.Scope) error {
	out.SourceType = in.SourceType
	out.SourceUUID = in.SourceUUID
	out.DeviceType = in.DeviceType
	out.Size = in.Size
	return nil
}

// Convert_v1alpha4_RootVolume_To_v1alpha5_RootVolume is an autogenerated conversion function.
func Convert_v1alpha4_RootVolume_To_v1alpha5_RootVolume(in *v1alpha4.RootVolume, out *RootVolume, s conversion.Scope) error {
	return autoConvert_v1alpha4_RootVolume_To_v1alpha5_RootVolume(in, out, s)
}

func autoConvert_v1alpha5_Router_To_v1alpha4_Router(in *Router, out *v1alpha4.Router, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha5_Router_To_v1alpha4_Router is an autogenerated conversion function.
func Convert_v1alpha5_Router_To_v1alpha4_Router(in *Router, out *v1alpha4.Router, s conversion.Scope) error {
	return autoConvert_v1alpha5_Router_To_v1alpha4_Router(in, out, s)
}

func autoConvert_v1alpha4_Router_To_v1alpha5_Router(in *v1alpha4.Router, out *Router, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha4_Router_To_v1alpha5_Router is an autogenerated conversion function.
func Convert_v1alpha4_Router_To_v1alpha5_Router(in *v1alpha4.Router, out *Router, s conversion.Scope) error {
	return autoConvert_v1alpha4_Router_To_v1alpha5_Router(in, out, s)
}

func autoConvert_v1alpha5_SecurityGroup_To_v1alpha4_SecurityGroup(in *SecurityGroup, out *v1alpha4.SecurityGroup, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.Rules = *(*[]v1alpha4.SecurityGroupRule)(unsafe.Pointer(&in.Rules))
	return nil
}

// Convert_v1alpha5_SecurityGroup_To_v1alpha4_SecurityGroup is an autogenerated conversion function.
func Convert_v1alpha5_SecurityGroup_To_v1alpha4_SecurityGroup(in *SecurityGroup, out *v1alpha4.SecurityGroup, s conversion.Scope) error {
	return autoConvert_v1alpha5_SecurityGroup_To_v1alpha4_SecurityGroup(in, out, s)
}

func autoConvert_v1alpha4_SecurityGroup_To_v1alpha5_SecurityGroup(in *v1alpha4.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.Rules = *(*[]SecurityGroupRule)(unsafe.Pointer(&in.Rules))
	return nil
}

// Convert_v1alpha4_SecurityGroup_To_v1alpha5_SecurityGroup is an autogenerated conversion function.
func Convert_v1alpha4_SecurityGroup_To_v1alpha5_SecurityGroup(in *v1alpha4.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	return autoConvert_v1alpha4_SecurityGroup_To_v1alpha5_SecurityGroup(in, out, s)
}

func autoConvert_v1alpha5_SecurityGroupFilter_To_v1alpha4_SecurityGroupFilter(in *SecurityGroupFilter, out *v1alpha4.SecurityGroupFilter, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.Description = in.Description
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.Limit = in.Limit
	out.Marker = in.Marker
	out.SortKey = in.SortKey
	out.SortDir = in.SortDir
	out.Tags = in.Tags
	out.TagsAny = in.TagsAny
	out.NotTags = in.NotTags
	out.NotTagsAny = in.NotTagsAny
	return nil
}

// Convert_v1alpha5_SecurityGroupFilter_To_v1alpha4_SecurityGroupFilter is an autogenerated conversion function.
func Convert_v1alpha5_SecurityGroupFilter_To_v1alpha4_SecurityGroupFilter(in *SecurityGroupFilter, out *v1alpha4.SecurityGroupFilter, s conversion.Scope) error {
	return autoConvert_v1alpha5_SecurityGroupFilter_To_v1alpha4_SecurityGroupFilter(in, out, s)
}

func autoConvert_v1alpha4_SecurityGroupFilter_To_v1alpha5_SecurityGroupFilter(in *v1alpha4.SecurityGroupFilter, out *SecurityGroupFilter, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	out.Description = in.Description
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.Limit = in.Limit
	out.Marker = in.Marker
	out.SortKey = in.SortKey
	out.SortDir = in.SortDir
	out.Tags = in.Tags
	out.TagsAny = in.TagsAny
	out.NotTags = in.NotTags
	out.NotTagsAny = in.NotTagsAny
	return nil
}

// Convert_v1alpha4_SecurityGroupFilter_To_v1alpha5_SecurityGroupFilter is an autogenerated conversion function.
func Convert_v1alpha4_SecurityGroupFilter_To_v1alpha5_SecurityGroupFilter(in *v1alpha4.SecurityGroupFilter, out *SecurityGroupFilter, s conversion.Scope) error {
	return autoConvert_v1alpha4_SecurityGroupFilter_To_v1alpha5_SecurityGroupFilter(in, out, s)
}

func autoConvert_v1alpha5_SecurityGroupParam_To_v1alpha4_SecurityGroupParam(in *SecurityGroupParam, out *v1alpha4.SecurityGroupParam, s conversion.Scope) error {
	out.UUID = in.UUID
	out.Name = in.Name
	if err := Convert_v1alpha5_SecurityGroupFilter_To_v1alpha4_SecurityGroupFilter(&in.Filter, &out.Filter, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_SecurityGroupParam_To_v1alpha4_SecurityGroupParam is an autogenerated conversion function.
func Convert_v1alpha5_SecurityGroupParam_To_v1alpha4_SecurityGroupParam(in *SecurityGroupParam, out *v1alpha4.SecurityGroupParam, s conversion.Scope) error {
	return autoConvert_v1alpha5_SecurityGroupParam_To_v1alpha4_SecurityGroupParam(in, out, s)
}

func autoConvert_v1alpha4_SecurityGroupParam_To_v1alpha5_SecurityGroupParam(in *v1alpha4.SecurityGroupParam, out *SecurityGroupParam, s conversion.Scope) error {
	out.UUID = in.UUID
	out.Name = in.Name
	if err := Convert_v1alpha4_SecurityGroupFilter_To_v1alpha5_SecurityGroupFilter(&in.Filter, &out.Filter, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_SecurityGroupParam_To_v1alpha5_SecurityGroupParam is an autogenerated conversion function.
func Convert_v1alpha4_SecurityGroupParam_To_v1alpha5_SecurityGroupParam(in *v1alpha4.SecurityGroupParam, out *SecurityGroupParam, s conversion.Scope) error {
	return autoConvert_v1alpha4_SecurityGroupParam_To_v1alpha5_SecurityGroupParam(in, out, s)
}

func autoConvert_v1alpha5_SecurityGroupRule_To_v1alpha4_SecurityGroupRule(in *SecurityGroupRule, out *v1alpha4.SecurityGroupRule, s conversion.Scope) error {
	out.Description = in.Description
	out.ID = in.ID
	out.Direction = in.Direction
	out.EtherType = in.EtherType
	out.SecurityGroupID = in.SecurityGroupID
	out.PortRangeMin = in.PortRangeMin
	out.PortRangeMax = in.PortRangeMax
	out.Protocol = in.Protocol
	out.RemoteGroupID = in.RemoteGroupID
	out.RemoteIPPrefix = in.RemoteIPPrefix
	return nil
}

// Convert_v1alpha5_SecurityGroupRule_To_v1alpha4_SecurityGroupRule is an autogenerated conversion function.
func Convert_v1alpha5_SecurityGroupRule_To_v1alpha4_SecurityGroupRule(in *SecurityGroupRule, out *v1alpha4.SecurityGroupRule, s conversion.Scope) error {
	return autoConvert_v1alpha5_SecurityGroupRule_To_v1alpha4_SecurityGroupRule(in, out, s)
}

func autoConvert_v1alpha4_SecurityGroupRule_To_v1alpha5_SecurityGroupRule(in *v1alpha4.SecurityGroupRule, out *SecurityGroupRule, s conversion.Scope) error {
	out.Description = in.Description
	out.ID = in.ID
	out.Direction = in.Direction
	out.EtherType = in.EtherType
	out.SecurityGroupID = in.SecurityGroupID
	out.PortRangeMin = in.PortRangeMin
	out.PortRangeMax = in.PortRangeMax
	out.Protocol = in.Protocol
	out.RemoteGroupID = in.RemoteGroupID
	out.RemoteIPPrefix = in.RemoteIPPrefix
	return nil
}

// Convert_v1alpha4_SecurityGroupRule_To_v1alpha5_SecurityGroupRule is an autogenerated conversion function.
func Convert_v1alpha4_SecurityGroupRule_To_v1alpha5_SecurityGroupRule(in *v1alpha4.SecurityGroupRule, out *SecurityGroupRule, s conversion.Scope) error {
	return autoConvert_v1alpha4_SecurityGroupRule_To_v1alpha5_SecurityGroupRule(in, out, s)
}

func autoConvert_v1alpha5_Subnet_To_v1alpha4_Subnet(in *Subnet, out *v1alpha4.Subnet, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.CIDR = in.CIDR
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha5_Subnet_To_v1alpha4_Subnet is an autogenerated conversion function.
func Convert_v1alpha5_Subnet_To_v1alpha4_Subnet(in *Subnet, out *v1alpha4.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha5_Subnet_To_v1alpha4_Subnet(in, out, s)
}

func autoConvert_v1alpha4_Subnet_To_v1alpha5_Subnet(in *v1alpha4.Subnet, out *Subnet, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	out.CIDR = in.CIDR
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha4_Subnet_To_v1alpha5_Subnet is an autogenerated conversion function.
func Convert_v1alpha4_Subnet_To_v1alpha5_Subnet(in *v1alpha4.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha4_Subnet_To_v1alpha5_Subnet(in, out, s)
}

func autoConvert_v1alpha5_SubnetFilter_To_v1alpha4_SubnetFilter(in *SubnetFilter, out *v1alpha4.SubnetFilter, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.EnableDHCP = (*bool)(unsafe.Pointer(in.EnableDHCP))
	out.NetworkID = in.NetworkID
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.IPVersion = in.IPVersion
	out.GatewayIP = in.GatewayIP
	out.CIDR = in.CIDR
	out.IPv6AddressMode = in.IPv6AddressMode
	out.IPv6RAMode = in.IPv6RAMode
	out.ID = in.ID
	out.SubnetPoolID = in.SubnetPoolID
	out.Limit = in.Limit
	out.Marker = in.Marker
	out.SortKey = in.SortKey
	out.SortDir = in.SortDir
	out.Tags = in.Tags
	out.TagsAny = in.TagsAny
	out.NotTags = in.NotTags
	out.NotTagsAny = in.NotTagsAny
	return nil
}

// Convert_v1alpha5_SubnetFilter_To_v1alpha4_SubnetFilter is an autogenerated conversion function.
func Convert_v1alpha5_SubnetFilter_To_v1alpha4_SubnetFilter(in *SubnetFilter, out *v1alpha4.SubnetFilter, s conversion.Scope) error {
	return autoConvert_v1alpha5_SubnetFilter_To_v1alpha4_SubnetFilter(in, out, s)
}

func autoConvert_v1alpha4_SubnetFilter_To_v1alpha5_SubnetFilter(in *v1alpha4.SubnetFilter, out *SubnetFilter, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.EnableDHCP = (*bool)(unsafe.Pointer(in.EnableDHCP))
	out.NetworkID = in.NetworkID
	out.TenantID = in.TenantID
	out.ProjectID = in.ProjectID
	out.IPVersion = in.IPVersion
	out.GatewayIP = in.GatewayIP
	out.CIDR = in.CIDR
	out.IPv6AddressMode = in.IPv6AddressMode
	out.IPv6RAMode = in.IPv6RAMode
	out.ID = in.ID
	out.SubnetPoolID = in.SubnetPoolID
	out.Limit = in.Limit
	out.Marker = in.Marker
	out.SortKey = in.SortKey
	out.SortDir = in.SortDir
	out.Tags = in.Tags
	out.TagsAny = in.TagsAny
	out.NotTags = in.NotTags
	out.NotTagsAny = in.NotTagsAny
	return nil
}

// Convert_v1alpha4_SubnetFilter_To_v1alpha5_SubnetFilter is an autogenerated conversion function.
func Convert_v1alpha4_SubnetFilter_To_v1alpha5_SubnetFilter(in *v1alpha4.SubnetFilter, out *SubnetFilter, s conversion.Scope) error {
	return autoConvert_v1alpha4_SubnetFilter_To_v1alpha5_SubnetFilter(in, out, s)
}

func autoConvert_v1alpha5_SubnetParam_To_v1alpha4_SubnetParam(in *SubnetParam, out *v1alpha4.SubnetParam, s conversion.Scope) error {
	out.UUID = in.UUID
	if err := Convert_v1alpha5_SubnetFilter_To_v1alpha4_SubnetFilter(&in.Filter, &out.Filter, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha5_SubnetParam_To_v1alpha4_SubnetParam is an autogenerated conversion function.
func Convert_v1alpha5_SubnetParam_To_v1alpha4_SubnetParam(in *SubnetParam, out *v1alpha4.SubnetParam, s conversion.Scope) error {
	return autoConvert_v1alpha5_SubnetParam_To_v1alpha4_SubnetParam(in, out, s)
}

func autoConvert_v1alpha4_SubnetParam_To_v1alpha5_SubnetParam(in *v1alpha4.SubnetParam, out *SubnetParam, s conversion.Scope) error {
	out.UUID = in.UUID
	if err := Convert_v1alpha4_SubnetFilter_To_v1alpha5_SubnetFilter(&in.Filter, &out.Filter, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_SubnetParam_To_v1alpha5_SubnetParam is an autogenerated conversion function.
func Convert_v1alpha4_SubnetParam_To_v1alpha5_SubnetParam(in *v1alpha4.SubnetParam, out *SubnetParam, s conversion.Scope) error {
	return autoConvert_v1alpha4_SubnetParam_To_v1alpha5_SubnetParam(in, out, s)
}
