/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package helpers

import (
	"slices"
	"strings"

	"k8s.io/utils/ptr"
	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	"sigs.k8s.io/randfill"

	infrav1beta1 "sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1"
	infrav1 "sigs.k8s.io/cluster-api-provider-openstack/api/v1beta2"
	"sigs.k8s.io/cluster-api-provider-openstack/pkg/utils/optional"
)

// filterInvalidTags removes tags that are empty or contain commas, which are
// rejected by API validation in both v1beta1 and v1beta2.
func filterInvalidTags[T ~string](tags []T) []T {
	var ret []T
	for i := range tags {
		s := string(tags[i])
		if s != "" && !strings.Contains(s, ",") {
			ret = append(ret, tags[i])
		}
	}
	return ret
}

func nonEmptyString(c randfill.Continue) string {
	for {
		if s := c.String(20); s != "" {
			return s
		}
	}
}

type isZeroer[T any] interface {
	IsZero() bool
	*T
}

func fuzzFilterParam[Z isZeroer[T], T any](id *optional.String, filter *Z, c randfill.Continue) {
	if c.Bool() {
		*id = ptr.To(nonEmptyString(c))
		*filter = nil
	} else {
		*filter = new(T)
		for (*filter).IsZero() {
			c.Fill(*filter)
		}
		*id = nil
	}
}

// fuzzVolumeAZ generates a valid VolumeAvailabilityZone configuration.
// Extracted as a helper to share between v1beta1 and v1beta2 fuzzer funcs.
func fuzzVolumeAZ[FromT ~string, NameT ~string](from *FromT, name **NameT, c randfill.Continue) {
	stringWithoutSpaces := func() string {
		for {
			s := c.String(20)
			if !strings.Contains(s, " ") && s != "" {
				return s
			}
		}
	}

	// From is defaulted
	if c.Bool() {
		n := NameT(stringWithoutSpaces())
		*name = &n
		return
	}

	// From is Name
	if c.Bool() {
		*from = FromT("Name")
		n := NameT(stringWithoutSpaces())
		*name = &n
		return
	}

	// From is Machine
	*from = FromT("Machine")
}

// ensureValidFlavorParam sets exactly one of ID or Filter.Name to a non-empty
// value, ensuring the FlavorParam satisfies conversion requirements.
func ensureValidFlavorParam(param *infrav1.FlavorParam, c randfill.Continue) {
	if c.Bool() {
		*param = infrav1.FlavorParam{
			ID: ptr.To(nonEmptyString(c)),
		}
	} else {
		*param = infrav1.FlavorParam{
			Filter: &infrav1.FlavorFilter{
				Name: ptr.To(nonEmptyString(c)),
			},
		}
	}
}

// InfraV1beta1FuzzerFuncs returns fuzzer funcs for v1beta1 OpenStack types which:
// * Constrain the output in ways which are validated by the API server
// * Add additional test coverage where it is not generated by the default fuzzer.
func InfraV1beta1FuzzerFuncs() []any {
	return []any{
		func(spec *infrav1beta1.OpenStackClusterSpec, c randfill.Continue) {
			c.FillNoCustom(spec)

			// The fuzzer only seems to generate Subnets of
			// length 1, but we need to also test length 2.
			// Ensure it is occasionally generated.
			if len(spec.Subnets) == 1 && c.Bool() {
				subnet := infrav1beta1.SubnetParam{}
				c.Fill(&subnet)
				spec.Subnets = append(spec.Subnets, subnet)
			}
		},

		func(spec *infrav1beta1.SubnetSpec, c randfill.Continue) {
			c.FillNoCustom(spec)

			// CIDR is required and API validates that it's present, so
			// we force it to always be set.
			for spec.CIDR == "" {
				spec.CIDR = c.String(20)
			}
		},

		func(pool *infrav1beta1.AllocationPool, c randfill.Continue) {
			c.FillNoCustom(pool)

			// Start and End are required properties, let's make sure both are set
			for pool.Start == "" {
				pool.Start = c.String(20)
			}

			for pool.End == "" {
				pool.End = c.String(20)
			}
		},

		// v1beta1 filter tags cannot contain commas and can't be empty.
		func(filter *infrav1beta1.FilterByNeutronTags, c randfill.Continue) {
			c.FillNoCustom(filter)

			// Sometimes add an additional tag to ensure we get test coverage of multiple tags
			if c.Bool() {
				filter.Tags = append(filter.Tags, infrav1beta1.NeutronTag(c.String(20)))
			}
			if c.Bool() {
				filter.TagsAny = append(filter.TagsAny, infrav1beta1.NeutronTag(c.String(20)))
			}
			if c.Bool() {
				filter.NotTags = append(filter.NotTags, infrav1beta1.NeutronTag(c.String(20)))
			}
			if c.Bool() {
				filter.NotTagsAny = append(filter.NotTagsAny, infrav1beta1.NeutronTag(c.String(20)))
			}

			// Remove empty tags and tags with commas
			filter.Tags = filterInvalidTags(filter.Tags)
			filter.TagsAny = filterInvalidTags(filter.TagsAny)
			filter.NotTags = filterInvalidTags(filter.NotTags)
			filter.NotTagsAny = filterInvalidTags(filter.NotTagsAny)
		},

		// v1beta1 filter params contain exactly one of ID or filter
		func(param *infrav1beta1.NetworkParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1beta1.SubnetParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1beta1.SecurityGroupParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1beta1.ImageParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1beta1.RouterParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		// Ensure at least one of Flavor or FlavorID is set (required for conversion)
		func(spec *infrav1beta1.OpenStackMachineSpec, c randfill.Continue) {
			c.FillNoCustom(spec)

			// Ensure non-empty if set (MinLength=1 validation)
			if spec.Flavor != nil && *spec.Flavor == "" {
				s := nonEmptyString(c)
				spec.Flavor = &s
			}
			if spec.FlavorID != nil && *spec.FlavorID == "" {
				s := nonEmptyString(c)
				spec.FlavorID = &s
			}
			// Ensure at least one is set
			if spec.Flavor == nil && spec.FlavorID == nil {
				if c.Bool() {
					s := nonEmptyString(c)
					spec.FlavorID = &s
				} else {
					s := nonEmptyString(c)
					spec.Flavor = &s
				}
			}
		},

		// Ensure VolumeAZ type is valid
		func(az *infrav1beta1.VolumeAvailabilityZone, c randfill.Continue) {
			fuzzVolumeAZ(&az.From, &az.Name, c)
		},
	}
}

// InfraV1Beta2FuzzerFuncs returns fuzzer funcs for v1beta2 OpenStack types which:
// * Constrain the output in ways which are validated by the API server
// * Constrain fields that are not preserved during v1beta2 <-> v1beta1 round-trip conversion
// * Add additional test coverage where it is not generated by the default fuzzer.
func InfraV1Beta2FuzzerFuncs() []any {
	return []any{
		// Normalize OpenStackCluster fields that are not preserved during
		// hub-spoke-hub conversion:
		// - ObservedGeneration on conditions is set from ObjectMeta.Generation during ConvertTo
		// - FailureDomains ordering is lost during map<->slice conversion
		func(cluster *infrav1.OpenStackCluster, c randfill.Continue) {
			c.FillNoCustom(cluster)

			// FillNoCustom does not invoke custom fuzzers for nested types,
			// so we explicitly ensure Flavor fields are valid for conversion.
			if cluster.Spec.Bastion != nil && cluster.Spec.Bastion.Spec != nil {
				ensureValidFlavorParam(&cluster.Spec.Bastion.Spec.Flavor, c)
			}

			for i := range cluster.Status.Conditions {
				cluster.Status.Conditions[i].ObservedGeneration = cluster.Generation
			}
			slices.SortFunc(cluster.Status.FailureDomains, func(a, b clusterv1.FailureDomain) int {
				return strings.Compare(a.Name, b.Name)
			})
		},

		// Normalize OpenStackMachine ObservedGeneration (set from ObjectMeta.Generation during ConvertTo).
		func(machine *infrav1.OpenStackMachine, c randfill.Continue) {
			c.FillNoCustom(machine)

			// FillNoCustom does not invoke custom fuzzers for nested types,
			// so we explicitly ensure Flavor is valid for conversion.
			ensureValidFlavorParam(&machine.Spec.Flavor, c)

			for i := range machine.Status.Conditions {
				machine.Status.Conditions[i].ObservedGeneration = machine.Generation
			}
		},

		// Normalize OpenStackMachineTemplate ObservedGeneration.
		// The template ConvertTo does not set ObservedGeneration, so it is
		// always zero after a hub-spoke-hub round-trip.
		func(tmpl *infrav1.OpenStackMachineTemplate, c randfill.Continue) {
			c.FillNoCustom(tmpl)

			// FillNoCustom does not invoke custom fuzzers for nested types,
			// so we explicitly ensure Flavor is valid for conversion.
			ensureValidFlavorParam(&tmpl.Spec.Template.Spec.Flavor, c)

			for i := range tmpl.Status.Conditions {
				tmpl.Status.Conditions[i].ObservedGeneration = 0
			}
		},

		func(spec *infrav1.OpenStackClusterSpec, c randfill.Continue) {
			c.FillNoCustom(spec)

			// The fuzzer only seems to generate Subnets of
			// length 1, but we need to also test length 2.
			// Ensure it is occasionally generated.
			if len(spec.Subnets) == 1 && c.Bool() {
				subnet := infrav1.SubnetParam{}
				c.Fill(&subnet)
				spec.Subnets = append(spec.Subnets, subnet)
			}
		},

		func(spec *infrav1.SubnetSpec, c randfill.Continue) {
			c.FillNoCustom(spec)

			// CIDR is required and API validates that it's present, so
			// we force it to always be set.
			for spec.CIDR == "" {
				spec.CIDR = c.String(20)
			}
		},

		func(pool *infrav1.AllocationPool, c randfill.Continue) {
			c.FillNoCustom(pool)

			// Start and End are required properties, let's make sure both are set
			for pool.Start == "" {
				pool.Start = c.String(20)
			}

			for pool.End == "" {
				pool.End = c.String(20)
			}
		},

		// v1beta2 filter tags cannot contain commas and can't be empty.
		func(filter *infrav1.FilterByNeutronTags, c randfill.Continue) {
			c.FillNoCustom(filter)

			// Sometimes add an additional tag to ensure we get test coverage of multiple tags
			if c.Bool() {
				filter.Tags = append(filter.Tags, infrav1.NeutronTag(c.String(20)))
			}
			if c.Bool() {
				filter.TagsAny = append(filter.TagsAny, infrav1.NeutronTag(c.String(20)))
			}
			if c.Bool() {
				filter.NotTags = append(filter.NotTags, infrav1.NeutronTag(c.String(20)))
			}
			if c.Bool() {
				filter.NotTagsAny = append(filter.NotTagsAny, infrav1.NeutronTag(c.String(20)))
			}

			// Remove empty tags and tags with commas
			filter.Tags = filterInvalidTags(filter.Tags)
			filter.TagsAny = filterInvalidTags(filter.TagsAny)
			filter.NotTags = filterInvalidTags(filter.NotTags)
			filter.NotTagsAny = filterInvalidTags(filter.NotTagsAny)
		},

		// ManagedNetwork must have at least one field set if non-nil.
		// This mirrors the CEL validation:
		//   self == null || has(self.mtu) || has(self.disablePortSecurity)
		func(mn **infrav1.ManagedNetwork, c randfill.Continue) {
			if c.Bool() {
				*mn = nil
				return
			}
			m := &infrav1.ManagedNetwork{}
			c.Fill(m)
			if m.MTU == nil && m.DisablePortSecurity == nil {
				m.MTU = ptr.To(int(c.Int31()))
			}
			*mn = m
		},

		// v1beta2 filter params contain exactly one of ID or filter
		func(param *infrav1.NetworkParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1.SubnetParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1.SecurityGroupParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1.ImageParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		func(param *infrav1.RouterParam, c randfill.Continue) {
			fuzzFilterParam(&param.ID, &param.Filter, c)
		},

		// Ensure FlavorParam has exactly one of ID or Filter with non-empty Name.
		// This mirrors the MinProperties/MaxProperties validation on FlavorParam.
		func(param *infrav1.FlavorParam, c randfill.Continue) {
			ensureValidFlavorParam(param, c)
		},

		// Ensure VolumeAZ type is valid
		func(az *infrav1.VolumeAvailabilityZone, c randfill.Continue) {
			fuzzVolumeAZ(&az.From, &az.Name, c)
		},

		// FailureDomains are converted via a map keyed by Name, so names
		// must be unique and non-empty. ControlPlane must be non-nil because
		// nil is converted to *false via ptr.Deref/ptr.To and won't
		// round-trip back to nil.
		func(fd *clusterv1.FailureDomain, c randfill.Continue) {
			c.FillNoCustom(fd)

			for fd.Name == "" {
				fd.Name = c.String(20)
			}
			if fd.ControlPlane == nil {
				fd.ControlPlane = ptr.To(c.Bool())
			}
		},

		// Deduplicate FailureDomain names at the status level since map
		// conversion collapses duplicates.
		func(status *infrav1.OpenStackClusterStatus, c randfill.Continue) {
			c.FillNoCustom(status)

			seen := map[string]bool{}
			unique := make([]clusterv1.FailureDomain, 0, len(status.FailureDomains))
			for _, fd := range status.FailureDomains {
				if !seen[fd.Name] {
					seen[fd.Name] = true
					unique = append(unique, fd)
				}
			}

			// Normalize empty slice to nil: v1beta1 round-trip cannot
			// distinguish between nil and empty slice.
			if len(unique) == 0 {
				status.FailureDomains = nil
			} else {
				status.FailureDomains = unique
			}
		},

		// ManagedRouter must have at least one ExternalIP if non-nil.
		// This mirrors the CEL validation:
		//   self == null || has(self.externalIPs)
		// An empty ManagedRouter cannot survive a hub-spoke-hub round-trip because
		// the conversion checks len(ExternalRouterIPs) > 0 before reconstructing it.
		func(mr **infrav1.ManagedRouter, c randfill.Continue) {
			if c.Bool() {
				*mr = nil
				return
			}
			m := &infrav1.ManagedRouter{}
			c.Fill(m)
			if len(m.ExternalIPs) == 0 {
				ip := infrav1.ExternalRouterIPParam{}
				c.Fill(&ip)
				m.ExternalIPs = []infrav1.ExternalRouterIPParam{ip}
			}
			*mr = m
		},
	}
}
