name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Buildkit
        uses: docker/setup-buildx-action@v2

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Authenticate with Quay.io
        if: ${{ github.event_name == 'push' || github.event_name == 'release' }}
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build image
        run: make docker-build-all
        env:
          REGISTRY: quay.io/vexxhost
          TAG: ${{ github.sha }}

      - name: Push image
        if: ${{ github.event_name == 'push' || github.event_name == 'release' }}
        run: make docker-push-all
        env:
          REGISTRY: quay.io/vexxhost
          TAG: ${{ github.sha }}

      - name: Promote image
        if: ${{ github.event_name == 'release' }}
        with:
          dst: quay.io/vexxhost/capi-openstack-controller:${{ github.sha }}
          src: quay.io/vexxhost/capi-openstack-controller:${{ github.event.release.name }}
