---
name: yamllint
on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install yamllint
      run: sudo apt-get update && sudo apt-get install -y yamllint

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: yaml-lint
      run: yamllint -c .yamllint.yaml .
